// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO2

package torch.torch

/** Represents all non-module code that the model depends on.
  * Right now it's just a straight list of classes, defined in dependency order
  * (i.e. dependencies appear before their dependers)
  */
@SerialVersionUID(0L)
final case class LibDef(
    torchscriptArena: _root_.scala.Option[torch.torch.RecordRef] = _root_.scala.None,
    unknownFields: _root_.scalapb.UnknownFieldSet = _root_.scalapb.UnknownFieldSet.empty
    ) extends scalapb.GeneratedMessage with scalapb.lenses.Updatable[LibDef] {
    @transient
    private[this] var __serializedSizeCachedValue: _root_.scala.Int = 0
    private[this] def __computeSerializedValue(): _root_.scala.Int = {
      var __size = 0
      if (torchscriptArena.isDefined) {
        val __value = torchscriptArena.get
        __size += 1 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(__value.serializedSize) + __value.serializedSize
      };
      __size += unknownFields.serializedSize
      __size
    }
    override def serializedSize: _root_.scala.Int = {
      var read = __serializedSizeCachedValue
      if (read == 0) {
        read = __computeSerializedValue()
        __serializedSizeCachedValue = read
      }
      read
    }
    def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): _root_.scala.Unit = {
      torchscriptArena.foreach { __v =>
        val __m = __v
        _output__.writeTag(1, 2)
        _output__.writeUInt32NoTag(__m.serializedSize)
        __m.writeTo(_output__)
      };
      unknownFields.writeTo(_output__)
    }
    def getTorchscriptArena: torch.torch.RecordRef = torchscriptArena.getOrElse(torch.torch.RecordRef.defaultInstance)
    def clearTorchscriptArena: LibDef = copy(torchscriptArena = _root_.scala.None)
    def withTorchscriptArena(__v: torch.torch.RecordRef): LibDef = copy(torchscriptArena = Option(__v))
    def withUnknownFields(__v: _root_.scalapb.UnknownFieldSet) = copy(unknownFields = __v)
    def discardUnknownFields = copy(unknownFields = _root_.scalapb.UnknownFieldSet.empty)
    def getFieldByNumber(__fieldNumber: _root_.scala.Int): _root_.scala.Any = {
      (__fieldNumber: @_root_.scala.unchecked) match {
        case 1 => torchscriptArena.orNull
      }
    }
    def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
      _root_.scala.Predef.require(__field.containingMessage eq companion.scalaDescriptor)
      (__field.number: @_root_.scala.unchecked) match {
        case 1 => torchscriptArena.map(_.toPMessage).getOrElse(_root_.scalapb.descriptors.PEmpty)
      }
    }
    def toProtoString: _root_.scala.Predef.String = _root_.scalapb.TextFormat.printToUnicodeString(this)
    def companion = torch.torch.LibDef
    // @@protoc_insertion_point(GeneratedMessage[torch.LibDef])
}

object LibDef extends scalapb.GeneratedMessageCompanion[torch.torch.LibDef] with scalapb.HasBuilder[torch.torch.LibDef] {
  implicit def messageCompanion: scalapb.GeneratedMessageCompanion[torch.torch.LibDef] with scalapb.HasBuilder[torch.torch.LibDef] = this
  def merge(`_message__`: torch.torch.LibDef, `_input__`: _root_.com.google.protobuf.CodedInputStream): torch.torch.LibDef = newBuilder(_message__).merge(_input__).result()
  implicit def messageReads: _root_.scalapb.descriptors.Reads[torch.torch.LibDef] = _root_.scalapb.descriptors.Reads{
    case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
      _root_.scala.Predef.require(__fieldsMap.keys.forall(_.containingMessage == scalaDescriptor), "FieldDescriptor does not match message type.")
      torch.torch.LibDef(
        torchscriptArena = __fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).flatMap(_.as[_root_.scala.Option[torch.torch.RecordRef]])
      )
    case _ => throw new RuntimeException("Expected PMessage")
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = TorchProto.javaDescriptor.getMessageTypes().get(5)
  def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = TorchProto.scalaDescriptor.messages(5)
  def messageCompanionForFieldNumber(__number: _root_.scala.Int): _root_.scalapb.GeneratedMessageCompanion[_] = {
    var __out: _root_.scalapb.GeneratedMessageCompanion[_] = null
    (__number: @_root_.scala.unchecked) match {
      case 1 => __out = torch.torch.RecordRef
    }
    __out
  }
  lazy val nestedMessagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] = Seq.empty
  def enumCompanionForFieldNumber(__fieldNumber: _root_.scala.Int): _root_.scalapb.GeneratedEnumCompanion[_] = throw new MatchError(__fieldNumber)
  lazy val defaultInstance = torch.torch.LibDef(
    torchscriptArena = _root_.scala.None
  )
  final class Builder private (
    private var __torchscriptArena: _root_.scala.Option[torch.torch.RecordRef],
    private var `_unknownFields__`: _root_.scalapb.UnknownFieldSet.Builder
  ) extends _root_.scalapb.MessageBuilder[torch.torch.LibDef] {
    def merge(`_input__`: _root_.com.google.protobuf.CodedInputStream): this.type = {
      var _done__ = false
      while (!_done__) {
        val _tag__ = _input__.readTag()
        _tag__ match {
          case 0 => _done__ = true
          case 10 =>
            __torchscriptArena = Option(__torchscriptArena.fold(_root_.scalapb.LiteParser.readMessage[torch.torch.RecordRef](_input__))(_root_.scalapb.LiteParser.readMessage(_input__, _)))
          case tag =>
            if (_unknownFields__ == null) {
              _unknownFields__ = new _root_.scalapb.UnknownFieldSet.Builder()
            }
            _unknownFields__.parseField(tag, _input__)
        }
      }
      this
    }
    def result(): torch.torch.LibDef = {
      torch.torch.LibDef(
        torchscriptArena = __torchscriptArena,
        unknownFields = if (_unknownFields__ == null) _root_.scalapb.UnknownFieldSet.empty else _unknownFields__.result()
      )
    }
  }
  object Builder extends _root_.scalapb.MessageBuilderCompanion[torch.torch.LibDef, torch.torch.LibDef.Builder] {
    def apply(): Builder = new Builder(
      __torchscriptArena = _root_.scala.None,
      `_unknownFields__` = null
    )
    def apply(`_message__`: torch.torch.LibDef): Builder = new Builder(
        __torchscriptArena = _message__.torchscriptArena,
        `_unknownFields__` = new _root_.scalapb.UnknownFieldSet.Builder(_message__.unknownFields)
    )
  }
  def newBuilder: Builder = torch.torch.LibDef.Builder()
  def newBuilder(`_message__`: torch.torch.LibDef): Builder = torch.torch.LibDef.Builder(_message__)
  implicit class LibDefLens[UpperPB](_l: _root_.scalapb.lenses.Lens[UpperPB, torch.torch.LibDef]) extends _root_.scalapb.lenses.ObjectLens[UpperPB, torch.torch.LibDef](_l) {
    def torchscriptArena: _root_.scalapb.lenses.Lens[UpperPB, torch.torch.RecordRef] = field(_.getTorchscriptArena)((c_, f_) => c_.copy(torchscriptArena = Option(f_)))
    def optionalTorchscriptArena: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Option[torch.torch.RecordRef]] = field(_.torchscriptArena)((c_, f_) => c_.copy(torchscriptArena = f_))
  }
  final val TORCHSCRIPT_ARENA_FIELD_NUMBER = 1
  def of(
    torchscriptArena: _root_.scala.Option[torch.torch.RecordRef]
  ): _root_.torch.torch.LibDef = _root_.torch.torch.LibDef(
    torchscriptArena
  )
  // @@protoc_insertion_point(GeneratedMessageCompanion[torch.LibDef])
}
