// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO2

package torch.torch

/** @param isBuffer
  *   whether this parameter is registered as buffer or not
  * @param tensorId
  *   the offset into the tensor table where this parameter is stored
  */
@SerialVersionUID(0L)
final case class ParameterDef(
    isBuffer: _root_.scala.Option[_root_.scala.Boolean] = _root_.scala.None,
    tensorId: _root_.scala.Option[_root_.scala.Long] = _root_.scala.None,
    name: _root_.scala.Option[_root_.scala.Predef.String] = _root_.scala.None,
    unknownFields: _root_.scalapb.UnknownFieldSet = _root_.scalapb.UnknownFieldSet.empty
    ) extends scalapb.GeneratedMessage with scalapb.lenses.Updatable[ParameterDef] {
    @transient
    private[this] var __serializedSizeCachedValue: _root_.scala.Int = 0
    private[this] def __computeSerializedValue(): _root_.scala.Int = {
      var __size = 0
      if (isBuffer.isDefined) {
        val __value = isBuffer.get
        __size += _root_.com.google.protobuf.CodedOutputStream.computeBoolSize(1, __value)
      };
      if (tensorId.isDefined) {
        val __value = tensorId.get
        __size += _root_.com.google.protobuf.CodedOutputStream.computeInt64Size(2, __value)
      };
      if (name.isDefined) {
        val __value = name.get
        __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(3, __value)
      };
      __size += unknownFields.serializedSize
      __size
    }
    override def serializedSize: _root_.scala.Int = {
      var read = __serializedSizeCachedValue
      if (read == 0) {
        read = __computeSerializedValue()
        __serializedSizeCachedValue = read
      }
      read
    }
    def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): _root_.scala.Unit = {
      isBuffer.foreach { __v =>
        val __m = __v
        _output__.writeBool(1, __m)
      };
      tensorId.foreach { __v =>
        val __m = __v
        _output__.writeInt64(2, __m)
      };
      name.foreach { __v =>
        val __m = __v
        _output__.writeString(3, __m)
      };
      unknownFields.writeTo(_output__)
    }
    def getIsBuffer: _root_.scala.Boolean = isBuffer.getOrElse(false)
    def clearIsBuffer: ParameterDef = copy(isBuffer = _root_.scala.None)
    def withIsBuffer(__v: _root_.scala.Boolean): ParameterDef = copy(isBuffer = Option(__v))
    def getTensorId: _root_.scala.Long = tensorId.getOrElse(0L)
    def clearTensorId: ParameterDef = copy(tensorId = _root_.scala.None)
    def withTensorId(__v: _root_.scala.Long): ParameterDef = copy(tensorId = Option(__v))
    def getName: _root_.scala.Predef.String = name.getOrElse("")
    def clearName: ParameterDef = copy(name = _root_.scala.None)
    def withName(__v: _root_.scala.Predef.String): ParameterDef = copy(name = Option(__v))
    def withUnknownFields(__v: _root_.scalapb.UnknownFieldSet) = copy(unknownFields = __v)
    def discardUnknownFields = copy(unknownFields = _root_.scalapb.UnknownFieldSet.empty)
    def getFieldByNumber(__fieldNumber: _root_.scala.Int): _root_.scala.Any = {
      (__fieldNumber: @_root_.scala.unchecked) match {
        case 1 => isBuffer.orNull
        case 2 => tensorId.orNull
        case 3 => name.orNull
      }
    }
    def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
      _root_.scala.Predef.require(__field.containingMessage eq companion.scalaDescriptor)
      (__field.number: @_root_.scala.unchecked) match {
        case 1 => isBuffer.map(_root_.scalapb.descriptors.PBoolean(_)).getOrElse(_root_.scalapb.descriptors.PEmpty)
        case 2 => tensorId.map(_root_.scalapb.descriptors.PLong(_)).getOrElse(_root_.scalapb.descriptors.PEmpty)
        case 3 => name.map(_root_.scalapb.descriptors.PString(_)).getOrElse(_root_.scalapb.descriptors.PEmpty)
      }
    }
    def toProtoString: _root_.scala.Predef.String = _root_.scalapb.TextFormat.printToUnicodeString(this)
    def companion = torch.torch.ParameterDef
    // @@protoc_insertion_point(GeneratedMessage[torch.ParameterDef])
}

object ParameterDef extends scalapb.GeneratedMessageCompanion[torch.torch.ParameterDef] with scalapb.HasBuilder[torch.torch.ParameterDef] {
  implicit def messageCompanion: scalapb.GeneratedMessageCompanion[torch.torch.ParameterDef] with scalapb.HasBuilder[torch.torch.ParameterDef] = this
  def merge(`_message__`: torch.torch.ParameterDef, `_input__`: _root_.com.google.protobuf.CodedInputStream): torch.torch.ParameterDef = newBuilder(_message__).merge(_input__).result()
  implicit def messageReads: _root_.scalapb.descriptors.Reads[torch.torch.ParameterDef] = _root_.scalapb.descriptors.Reads{
    case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
      _root_.scala.Predef.require(__fieldsMap.keys.forall(_.containingMessage == scalaDescriptor), "FieldDescriptor does not match message type.")
      torch.torch.ParameterDef(
        isBuffer = __fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).flatMap(_.as[_root_.scala.Option[_root_.scala.Boolean]]),
        tensorId = __fieldsMap.get(scalaDescriptor.findFieldByNumber(2).get).flatMap(_.as[_root_.scala.Option[_root_.scala.Long]]),
        name = __fieldsMap.get(scalaDescriptor.findFieldByNumber(3).get).flatMap(_.as[_root_.scala.Option[_root_.scala.Predef.String]])
      )
    case _ => throw new RuntimeException("Expected PMessage")
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = TorchProto.javaDescriptor.getMessageTypes().get(3)
  def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = TorchProto.scalaDescriptor.messages(3)
  def messageCompanionForFieldNumber(__number: _root_.scala.Int): _root_.scalapb.GeneratedMessageCompanion[_] = throw new MatchError(__number)
  lazy val nestedMessagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] = Seq.empty
  def enumCompanionForFieldNumber(__fieldNumber: _root_.scala.Int): _root_.scalapb.GeneratedEnumCompanion[_] = throw new MatchError(__fieldNumber)
  lazy val defaultInstance = torch.torch.ParameterDef(
    isBuffer = _root_.scala.None,
    tensorId = _root_.scala.None,
    name = _root_.scala.None
  )
  final class Builder private (
    private var __isBuffer: _root_.scala.Option[_root_.scala.Boolean],
    private var __tensorId: _root_.scala.Option[_root_.scala.Long],
    private var __name: _root_.scala.Option[_root_.scala.Predef.String],
    private var `_unknownFields__`: _root_.scalapb.UnknownFieldSet.Builder
  ) extends _root_.scalapb.MessageBuilder[torch.torch.ParameterDef] {
    def merge(`_input__`: _root_.com.google.protobuf.CodedInputStream): this.type = {
      var _done__ = false
      while (!_done__) {
        val _tag__ = _input__.readTag()
        _tag__ match {
          case 0 => _done__ = true
          case 8 =>
            __isBuffer = Option(_input__.readBool())
          case 16 =>
            __tensorId = Option(_input__.readInt64())
          case 26 =>
            __name = Option(_input__.readStringRequireUtf8())
          case tag =>
            if (_unknownFields__ == null) {
              _unknownFields__ = new _root_.scalapb.UnknownFieldSet.Builder()
            }
            _unknownFields__.parseField(tag, _input__)
        }
      }
      this
    }
    def result(): torch.torch.ParameterDef = {
      torch.torch.ParameterDef(
        isBuffer = __isBuffer,
        tensorId = __tensorId,
        name = __name,
        unknownFields = if (_unknownFields__ == null) _root_.scalapb.UnknownFieldSet.empty else _unknownFields__.result()
      )
    }
  }
  object Builder extends _root_.scalapb.MessageBuilderCompanion[torch.torch.ParameterDef, torch.torch.ParameterDef.Builder] {
    def apply(): Builder = new Builder(
      __isBuffer = _root_.scala.None,
      __tensorId = _root_.scala.None,
      __name = _root_.scala.None,
      `_unknownFields__` = null
    )
    def apply(`_message__`: torch.torch.ParameterDef): Builder = new Builder(
        __isBuffer = _message__.isBuffer,
        __tensorId = _message__.tensorId,
        __name = _message__.name,
        `_unknownFields__` = new _root_.scalapb.UnknownFieldSet.Builder(_message__.unknownFields)
    )
  }
  def newBuilder: Builder = torch.torch.ParameterDef.Builder()
  def newBuilder(`_message__`: torch.torch.ParameterDef): Builder = torch.torch.ParameterDef.Builder(_message__)
  implicit class ParameterDefLens[UpperPB](_l: _root_.scalapb.lenses.Lens[UpperPB, torch.torch.ParameterDef]) extends _root_.scalapb.lenses.ObjectLens[UpperPB, torch.torch.ParameterDef](_l) {
    def isBuffer: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Boolean] = field(_.getIsBuffer)((c_, f_) => c_.copy(isBuffer = Option(f_)))
    def optionalIsBuffer: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Option[_root_.scala.Boolean]] = field(_.isBuffer)((c_, f_) => c_.copy(isBuffer = f_))
    def tensorId: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Long] = field(_.getTensorId)((c_, f_) => c_.copy(tensorId = Option(f_)))
    def optionalTensorId: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Option[_root_.scala.Long]] = field(_.tensorId)((c_, f_) => c_.copy(tensorId = f_))
    def name: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.getName)((c_, f_) => c_.copy(name = Option(f_)))
    def optionalName: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Option[_root_.scala.Predef.String]] = field(_.name)((c_, f_) => c_.copy(name = f_))
  }
  final val IS_BUFFER_FIELD_NUMBER = 1
  final val TENSOR_ID_FIELD_NUMBER = 2
  final val NAME_FIELD_NUMBER = 3
  def of(
    isBuffer: _root_.scala.Option[_root_.scala.Boolean],
    tensorId: _root_.scala.Option[_root_.scala.Long],
    name: _root_.scala.Option[_root_.scala.Predef.String]
  ): _root_.torch.torch.ParameterDef = _root_.torch.torch.ParameterDef(
    isBuffer,
    tensorId,
    name
  )
  // @@protoc_insertion_point(GeneratedMessageCompanion[torch.ParameterDef])
}
