// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO2

package caffe2.metanet

@SerialVersionUID(0L)
final case class BlobsMap(
    key: _root_.scala.Predef.String,
    value: _root_.scala.Seq[_root_.scala.Predef.String] = _root_.scala.Seq.empty,
    unknownFields: _root_.scalapb.UnknownFieldSet = _root_.scalapb.UnknownFieldSet.empty
    ) extends scalapb.GeneratedMessage with scalapb.lenses.Updatable[BlobsMap] {
    @transient
    private[this] var __serializedSizeCachedValue: _root_.scala.Int = 0
    private[this] def __computeSerializedValue(): _root_.scala.Int = {
      var __size = 0
      
      {
        val __value = key
        __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(1, __value)
      };
      value.foreach { __item =>
        val __value = __item
        __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(2, __value)
      }
      __size += unknownFields.serializedSize
      __size
    }
    override def serializedSize: _root_.scala.Int = {
      var read = __serializedSizeCachedValue
      if (read == 0) {
        read = __computeSerializedValue()
        __serializedSizeCachedValue = read
      }
      read
    }
    def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): _root_.scala.Unit = {
      
      {
        val __v = key
        _output__.writeString(1, __v)
      };
      value.foreach { __v =>
        val __m = __v
        _output__.writeString(2, __m)
      };
      unknownFields.writeTo(_output__)
    }
    def withKey(__v: _root_.scala.Predef.String): BlobsMap = copy(key = __v)
    def clearValue = copy(value = _root_.scala.Seq.empty)
    def addValue(__vs: _root_.scala.Predef.String*): BlobsMap = addAllValue(__vs)
    def addAllValue(__vs: Iterable[_root_.scala.Predef.String]): BlobsMap = copy(value = value ++ __vs)
    def withValue(__v: _root_.scala.Seq[_root_.scala.Predef.String]): BlobsMap = copy(value = __v)
    def withUnknownFields(__v: _root_.scalapb.UnknownFieldSet) = copy(unknownFields = __v)
    def discardUnknownFields = copy(unknownFields = _root_.scalapb.UnknownFieldSet.empty)
    def getFieldByNumber(__fieldNumber: _root_.scala.Int): _root_.scala.Any = {
      (__fieldNumber: @_root_.scala.unchecked) match {
        case 1 => key
        case 2 => value
      }
    }
    def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
      _root_.scala.Predef.require(__field.containingMessage eq companion.scalaDescriptor)
      (__field.number: @_root_.scala.unchecked) match {
        case 1 => _root_.scalapb.descriptors.PString(key)
        case 2 => _root_.scalapb.descriptors.PRepeated(value.iterator.map(_root_.scalapb.descriptors.PString(_)).toVector)
      }
    }
    def toProtoString: _root_.scala.Predef.String = _root_.scalapb.TextFormat.printToUnicodeString(this)
    def companion = caffe2.metanet.BlobsMap
    // @@protoc_insertion_point(GeneratedMessage[caffe2.BlobsMap])
}

object BlobsMap extends scalapb.GeneratedMessageCompanion[caffe2.metanet.BlobsMap] with scalapb.HasBuilder[caffe2.metanet.BlobsMap] {
  implicit def messageCompanion: scalapb.GeneratedMessageCompanion[caffe2.metanet.BlobsMap] with scalapb.HasBuilder[caffe2.metanet.BlobsMap] = this
  def merge(`_message__`: caffe2.metanet.BlobsMap, `_input__`: _root_.com.google.protobuf.CodedInputStream): caffe2.metanet.BlobsMap = newBuilder(_message__).merge(_input__).result()
  implicit def messageReads: _root_.scalapb.descriptors.Reads[caffe2.metanet.BlobsMap] = _root_.scalapb.descriptors.Reads{
    case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
      _root_.scala.Predef.require(__fieldsMap.keys.forall(_.containingMessage == scalaDescriptor), "FieldDescriptor does not match message type.")
      caffe2.metanet.BlobsMap(
        key = __fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).get.as[_root_.scala.Predef.String],
        value = __fieldsMap.get(scalaDescriptor.findFieldByNumber(2).get).map(_.as[_root_.scala.Seq[_root_.scala.Predef.String]]).getOrElse(_root_.scala.Seq.empty)
      )
    case _ => throw new RuntimeException("Expected PMessage")
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = MetanetProto.javaDescriptor.getMessageTypes().get(1)
  def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = MetanetProto.scalaDescriptor.messages(1)
  def messageCompanionForFieldNumber(__number: _root_.scala.Int): _root_.scalapb.GeneratedMessageCompanion[_] = throw new MatchError(__number)
  lazy val nestedMessagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] = Seq.empty
  def enumCompanionForFieldNumber(__fieldNumber: _root_.scala.Int): _root_.scalapb.GeneratedEnumCompanion[_] = throw new MatchError(__fieldNumber)
  lazy val defaultInstance = caffe2.metanet.BlobsMap(
    key = "",
    value = _root_.scala.Seq.empty
  )
  final class Builder private (
    private var __key: _root_.scala.Predef.String,
    private val __value: _root_.scala.collection.immutable.VectorBuilder[_root_.scala.Predef.String],
    private var `_unknownFields__`: _root_.scalapb.UnknownFieldSet.Builder
  ) extends _root_.scalapb.MessageBuilder[caffe2.metanet.BlobsMap] {
    private var __requiredFields0: _root_.scala.Long = 0x1L
    def merge(`_input__`: _root_.com.google.protobuf.CodedInputStream): this.type = {
      var _done__ = false
      while (!_done__) {
        val _tag__ = _input__.readTag()
        _tag__ match {
          case 0 => _done__ = true
          case 10 =>
            __key = _input__.readStringRequireUtf8()
            __requiredFields0 &= 0xfffffffffffffffeL
          case 18 =>
            __value += _input__.readStringRequireUtf8()
          case tag =>
            if (_unknownFields__ == null) {
              _unknownFields__ = new _root_.scalapb.UnknownFieldSet.Builder()
            }
            _unknownFields__.parseField(tag, _input__)
        }
      }
      this
    }
    def result(): caffe2.metanet.BlobsMap = {
      if (__requiredFields0 != 0L) { throw new _root_.com.google.protobuf.InvalidProtocolBufferException("Message missing required fields.") } 
      caffe2.metanet.BlobsMap(
        key = __key,
        value = __value.result(),
        unknownFields = if (_unknownFields__ == null) _root_.scalapb.UnknownFieldSet.empty else _unknownFields__.result()
      )
    }
  }
  object Builder extends _root_.scalapb.MessageBuilderCompanion[caffe2.metanet.BlobsMap, caffe2.metanet.BlobsMap.Builder] {
    def apply(): Builder = new Builder(
      __key = "",
      __value = new _root_.scala.collection.immutable.VectorBuilder[_root_.scala.Predef.String],
      `_unknownFields__` = null
    )
    def apply(`_message__`: caffe2.metanet.BlobsMap): Builder = new Builder(
        __key = _message__.key,
        __value = new _root_.scala.collection.immutable.VectorBuilder[_root_.scala.Predef.String] ++= _message__.value,
        `_unknownFields__` = new _root_.scalapb.UnknownFieldSet.Builder(_message__.unknownFields)
    )
  }
  def newBuilder: Builder = caffe2.metanet.BlobsMap.Builder()
  def newBuilder(`_message__`: caffe2.metanet.BlobsMap): Builder = caffe2.metanet.BlobsMap.Builder(_message__)
  implicit class BlobsMapLens[UpperPB](_l: _root_.scalapb.lenses.Lens[UpperPB, caffe2.metanet.BlobsMap]) extends _root_.scalapb.lenses.ObjectLens[UpperPB, caffe2.metanet.BlobsMap](_l) {
    def key: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.key)((c_, f_) => c_.copy(key = f_))
    def value: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Seq[_root_.scala.Predef.String]] = field(_.value)((c_, f_) => c_.copy(value = f_))
  }
  final val KEY_FIELD_NUMBER = 1
  final val VALUE_FIELD_NUMBER = 2
  def of(
    key: _root_.scala.Predef.String,
    value: _root_.scala.Seq[_root_.scala.Predef.String]
  ): _root_.caffe2.metanet.BlobsMap = _root_.caffe2.metanet.BlobsMap(
    key,
    value
  )
  // @@protoc_insertion_point(GeneratedMessageCompanion[caffe2.BlobsMap])
}
