// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO2

package caffe2.caffe2

/** Protobuf format to serialize DBReader.
  *
  * @param name
  *   The name for the DB object in the workspace.
  * @param source
  *   The source of the DB
  * @param dbType
  *   The type of the DB
  * @param key
  *   The current key of the DB if the DB supports seeking.
  */
@SerialVersionUID(0L)
final case class DBReaderProto(
    name: _root_.scala.Option[_root_.scala.Predef.String] = _root_.scala.None,
    source: _root_.scala.Option[_root_.scala.Predef.String] = _root_.scala.None,
    dbType: _root_.scala.Option[_root_.scala.Predef.String] = _root_.scala.None,
    key: _root_.scala.Option[_root_.scala.Predef.String] = _root_.scala.None,
    unknownFields: _root_.scalapb.UnknownFieldSet = _root_.scalapb.UnknownFieldSet.empty
    ) extends scalapb.GeneratedMessage with scalapb.lenses.Updatable[DBReaderProto] {
    @transient
    private[this] var __serializedSizeCachedValue: _root_.scala.Int = 0
    private[this] def __computeSerializedValue(): _root_.scala.Int = {
      var __size = 0
      if (name.isDefined) {
        val __value = name.get
        __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(1, __value)
      };
      if (source.isDefined) {
        val __value = source.get
        __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(2, __value)
      };
      if (dbType.isDefined) {
        val __value = dbType.get
        __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(3, __value)
      };
      if (key.isDefined) {
        val __value = key.get
        __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(4, __value)
      };
      __size += unknownFields.serializedSize
      __size
    }
    override def serializedSize: _root_.scala.Int = {
      var read = __serializedSizeCachedValue
      if (read == 0) {
        read = __computeSerializedValue()
        __serializedSizeCachedValue = read
      }
      read
    }
    def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): _root_.scala.Unit = {
      name.foreach { __v =>
        val __m = __v
        _output__.writeString(1, __m)
      };
      source.foreach { __v =>
        val __m = __v
        _output__.writeString(2, __m)
      };
      dbType.foreach { __v =>
        val __m = __v
        _output__.writeString(3, __m)
      };
      key.foreach { __v =>
        val __m = __v
        _output__.writeString(4, __m)
      };
      unknownFields.writeTo(_output__)
    }
    def getName: _root_.scala.Predef.String = name.getOrElse("")
    def clearName: DBReaderProto = copy(name = _root_.scala.None)
    def withName(__v: _root_.scala.Predef.String): DBReaderProto = copy(name = Option(__v))
    def getSource: _root_.scala.Predef.String = source.getOrElse("")
    def clearSource: DBReaderProto = copy(source = _root_.scala.None)
    def withSource(__v: _root_.scala.Predef.String): DBReaderProto = copy(source = Option(__v))
    def getDbType: _root_.scala.Predef.String = dbType.getOrElse("")
    def clearDbType: DBReaderProto = copy(dbType = _root_.scala.None)
    def withDbType(__v: _root_.scala.Predef.String): DBReaderProto = copy(dbType = Option(__v))
    def getKey: _root_.scala.Predef.String = key.getOrElse("")
    def clearKey: DBReaderProto = copy(key = _root_.scala.None)
    def withKey(__v: _root_.scala.Predef.String): DBReaderProto = copy(key = Option(__v))
    def withUnknownFields(__v: _root_.scalapb.UnknownFieldSet) = copy(unknownFields = __v)
    def discardUnknownFields = copy(unknownFields = _root_.scalapb.UnknownFieldSet.empty)
    def getFieldByNumber(__fieldNumber: _root_.scala.Int): _root_.scala.Any = {
      (__fieldNumber: @_root_.scala.unchecked) match {
        case 1 => name.orNull
        case 2 => source.orNull
        case 3 => dbType.orNull
        case 4 => key.orNull
      }
    }
    def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
      _root_.scala.Predef.require(__field.containingMessage eq companion.scalaDescriptor)
      (__field.number: @_root_.scala.unchecked) match {
        case 1 => name.map(_root_.scalapb.descriptors.PString(_)).getOrElse(_root_.scalapb.descriptors.PEmpty)
        case 2 => source.map(_root_.scalapb.descriptors.PString(_)).getOrElse(_root_.scalapb.descriptors.PEmpty)
        case 3 => dbType.map(_root_.scalapb.descriptors.PString(_)).getOrElse(_root_.scalapb.descriptors.PEmpty)
        case 4 => key.map(_root_.scalapb.descriptors.PString(_)).getOrElse(_root_.scalapb.descriptors.PEmpty)
      }
    }
    def toProtoString: _root_.scala.Predef.String = _root_.scalapb.TextFormat.printToUnicodeString(this)
    def companion = caffe2.caffe2.DBReaderProto
    // @@protoc_insertion_point(GeneratedMessage[caffe2.DBReaderProto])
}

object DBReaderProto extends scalapb.GeneratedMessageCompanion[caffe2.caffe2.DBReaderProto] with scalapb.HasBuilder[caffe2.caffe2.DBReaderProto] {
  implicit def messageCompanion: scalapb.GeneratedMessageCompanion[caffe2.caffe2.DBReaderProto] with scalapb.HasBuilder[caffe2.caffe2.DBReaderProto] = this
  def merge(`_message__`: caffe2.caffe2.DBReaderProto, `_input__`: _root_.com.google.protobuf.CodedInputStream): caffe2.caffe2.DBReaderProto = newBuilder(_message__).merge(_input__).result()
  implicit def messageReads: _root_.scalapb.descriptors.Reads[caffe2.caffe2.DBReaderProto] = _root_.scalapb.descriptors.Reads{
    case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
      _root_.scala.Predef.require(__fieldsMap.keys.forall(_.containingMessage == scalaDescriptor), "FieldDescriptor does not match message type.")
      caffe2.caffe2.DBReaderProto(
        name = __fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).flatMap(_.as[_root_.scala.Option[_root_.scala.Predef.String]]),
        source = __fieldsMap.get(scalaDescriptor.findFieldByNumber(2).get).flatMap(_.as[_root_.scala.Option[_root_.scala.Predef.String]]),
        dbType = __fieldsMap.get(scalaDescriptor.findFieldByNumber(3).get).flatMap(_.as[_root_.scala.Option[_root_.scala.Predef.String]]),
        key = __fieldsMap.get(scalaDescriptor.findFieldByNumber(4).get).flatMap(_.as[_root_.scala.Option[_root_.scala.Predef.String]])
      )
    case _ => throw new RuntimeException("Expected PMessage")
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = Caffe2Proto.javaDescriptor.getMessageTypes().get(19)
  def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = Caffe2Proto.scalaDescriptor.messages(19)
  def messageCompanionForFieldNumber(__number: _root_.scala.Int): _root_.scalapb.GeneratedMessageCompanion[_] = throw new MatchError(__number)
  lazy val nestedMessagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] = Seq.empty
  def enumCompanionForFieldNumber(__fieldNumber: _root_.scala.Int): _root_.scalapb.GeneratedEnumCompanion[_] = throw new MatchError(__fieldNumber)
  lazy val defaultInstance = caffe2.caffe2.DBReaderProto(
    name = _root_.scala.None,
    source = _root_.scala.None,
    dbType = _root_.scala.None,
    key = _root_.scala.None
  )
  final class Builder private (
    private var __name: _root_.scala.Option[_root_.scala.Predef.String],
    private var __source: _root_.scala.Option[_root_.scala.Predef.String],
    private var __dbType: _root_.scala.Option[_root_.scala.Predef.String],
    private var __key: _root_.scala.Option[_root_.scala.Predef.String],
    private var `_unknownFields__`: _root_.scalapb.UnknownFieldSet.Builder
  ) extends _root_.scalapb.MessageBuilder[caffe2.caffe2.DBReaderProto] {
    def merge(`_input__`: _root_.com.google.protobuf.CodedInputStream): this.type = {
      var _done__ = false
      while (!_done__) {
        val _tag__ = _input__.readTag()
        _tag__ match {
          case 0 => _done__ = true
          case 10 =>
            __name = Option(_input__.readStringRequireUtf8())
          case 18 =>
            __source = Option(_input__.readStringRequireUtf8())
          case 26 =>
            __dbType = Option(_input__.readStringRequireUtf8())
          case 34 =>
            __key = Option(_input__.readStringRequireUtf8())
          case tag =>
            if (_unknownFields__ == null) {
              _unknownFields__ = new _root_.scalapb.UnknownFieldSet.Builder()
            }
            _unknownFields__.parseField(tag, _input__)
        }
      }
      this
    }
    def result(): caffe2.caffe2.DBReaderProto = {
      caffe2.caffe2.DBReaderProto(
        name = __name,
        source = __source,
        dbType = __dbType,
        key = __key,
        unknownFields = if (_unknownFields__ == null) _root_.scalapb.UnknownFieldSet.empty else _unknownFields__.result()
      )
    }
  }
  object Builder extends _root_.scalapb.MessageBuilderCompanion[caffe2.caffe2.DBReaderProto, caffe2.caffe2.DBReaderProto.Builder] {
    def apply(): Builder = new Builder(
      __name = _root_.scala.None,
      __source = _root_.scala.None,
      __dbType = _root_.scala.None,
      __key = _root_.scala.None,
      `_unknownFields__` = null
    )
    def apply(`_message__`: caffe2.caffe2.DBReaderProto): Builder = new Builder(
        __name = _message__.name,
        __source = _message__.source,
        __dbType = _message__.dbType,
        __key = _message__.key,
        `_unknownFields__` = new _root_.scalapb.UnknownFieldSet.Builder(_message__.unknownFields)
    )
  }
  def newBuilder: Builder = caffe2.caffe2.DBReaderProto.Builder()
  def newBuilder(`_message__`: caffe2.caffe2.DBReaderProto): Builder = caffe2.caffe2.DBReaderProto.Builder(_message__)
  implicit class DBReaderProtoLens[UpperPB](_l: _root_.scalapb.lenses.Lens[UpperPB, caffe2.caffe2.DBReaderProto]) extends _root_.scalapb.lenses.ObjectLens[UpperPB, caffe2.caffe2.DBReaderProto](_l) {
    def name: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.getName)((c_, f_) => c_.copy(name = Option(f_)))
    def optionalName: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Option[_root_.scala.Predef.String]] = field(_.name)((c_, f_) => c_.copy(name = f_))
    def source: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.getSource)((c_, f_) => c_.copy(source = Option(f_)))
    def optionalSource: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Option[_root_.scala.Predef.String]] = field(_.source)((c_, f_) => c_.copy(source = f_))
    def dbType: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.getDbType)((c_, f_) => c_.copy(dbType = Option(f_)))
    def optionalDbType: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Option[_root_.scala.Predef.String]] = field(_.dbType)((c_, f_) => c_.copy(dbType = f_))
    def key: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.getKey)((c_, f_) => c_.copy(key = Option(f_)))
    def optionalKey: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Option[_root_.scala.Predef.String]] = field(_.key)((c_, f_) => c_.copy(key = f_))
  }
  final val NAME_FIELD_NUMBER = 1
  final val SOURCE_FIELD_NUMBER = 2
  final val DB_TYPE_FIELD_NUMBER = 3
  final val KEY_FIELD_NUMBER = 4
  def of(
    name: _root_.scala.Option[_root_.scala.Predef.String],
    source: _root_.scala.Option[_root_.scala.Predef.String],
    dbType: _root_.scala.Option[_root_.scala.Predef.String],
    key: _root_.scala.Option[_root_.scala.Predef.String]
  ): _root_.caffe2.caffe2.DBReaderProto = _root_.caffe2.caffe2.DBReaderProto(
    name,
    source,
    dbType,
    key
  )
  // @@protoc_insertion_point(GeneratedMessageCompanion[caffe2.DBReaderProto])
}
