// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO2

package caffe2.caffe2

@SerialVersionUID(0L)
final case class TensorShapes(
    shapes: _root_.scala.Seq[caffe2.caffe2.TensorShape] = _root_.scala.Seq.empty,
    unknownFields: _root_.scalapb.UnknownFieldSet = _root_.scalapb.UnknownFieldSet.empty
    ) extends scalapb.GeneratedMessage with scalapb.lenses.Updatable[TensorShapes] {
    @transient
    private[this] var __serializedSizeCachedValue: _root_.scala.Int = 0
    private[this] def __computeSerializedValue(): _root_.scala.Int = {
      var __size = 0
      shapes.foreach { __item =>
        val __value = __item
        __size += 1 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(__value.serializedSize) + __value.serializedSize
      }
      __size += unknownFields.serializedSize
      __size
    }
    override def serializedSize: _root_.scala.Int = {
      var read = __serializedSizeCachedValue
      if (read == 0) {
        read = __computeSerializedValue()
        __serializedSizeCachedValue = read
      }
      read
    }
    def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): _root_.scala.Unit = {
      shapes.foreach { __v =>
        val __m = __v
        _output__.writeTag(1, 2)
        _output__.writeUInt32NoTag(__m.serializedSize)
        __m.writeTo(_output__)
      };
      unknownFields.writeTo(_output__)
    }
    def clearShapes = copy(shapes = _root_.scala.Seq.empty)
    def addShapes(__vs: caffe2.caffe2.TensorShape*): TensorShapes = addAllShapes(__vs)
    def addAllShapes(__vs: Iterable[caffe2.caffe2.TensorShape]): TensorShapes = copy(shapes = shapes ++ __vs)
    def withShapes(__v: _root_.scala.Seq[caffe2.caffe2.TensorShape]): TensorShapes = copy(shapes = __v)
    def withUnknownFields(__v: _root_.scalapb.UnknownFieldSet) = copy(unknownFields = __v)
    def discardUnknownFields = copy(unknownFields = _root_.scalapb.UnknownFieldSet.empty)
    def getFieldByNumber(__fieldNumber: _root_.scala.Int): _root_.scala.Any = {
      (__fieldNumber: @_root_.scala.unchecked) match {
        case 1 => shapes
      }
    }
    def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
      _root_.scala.Predef.require(__field.containingMessage eq companion.scalaDescriptor)
      (__field.number: @_root_.scala.unchecked) match {
        case 1 => _root_.scalapb.descriptors.PRepeated(shapes.iterator.map(_.toPMessage).toVector)
      }
    }
    def toProtoString: _root_.scala.Predef.String = _root_.scalapb.TextFormat.printToUnicodeString(this)
    def companion = caffe2.caffe2.TensorShapes
    // @@protoc_insertion_point(GeneratedMessage[caffe2.TensorShapes])
}

object TensorShapes extends scalapb.GeneratedMessageCompanion[caffe2.caffe2.TensorShapes] with scalapb.HasBuilder[caffe2.caffe2.TensorShapes] {
  implicit def messageCompanion: scalapb.GeneratedMessageCompanion[caffe2.caffe2.TensorShapes] with scalapb.HasBuilder[caffe2.caffe2.TensorShapes] = this
  def merge(`_message__`: caffe2.caffe2.TensorShapes, `_input__`: _root_.com.google.protobuf.CodedInputStream): caffe2.caffe2.TensorShapes = newBuilder(_message__).merge(_input__).result()
  implicit def messageReads: _root_.scalapb.descriptors.Reads[caffe2.caffe2.TensorShapes] = _root_.scalapb.descriptors.Reads{
    case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
      _root_.scala.Predef.require(__fieldsMap.keys.forall(_.containingMessage == scalaDescriptor), "FieldDescriptor does not match message type.")
      caffe2.caffe2.TensorShapes(
        shapes = __fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).map(_.as[_root_.scala.Seq[caffe2.caffe2.TensorShape]]).getOrElse(_root_.scala.Seq.empty)
      )
    case _ => throw new RuntimeException("Expected PMessage")
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = Caffe2Proto.javaDescriptor.getMessageTypes().get(5)
  def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = Caffe2Proto.scalaDescriptor.messages(5)
  def messageCompanionForFieldNumber(__number: _root_.scala.Int): _root_.scalapb.GeneratedMessageCompanion[_] = {
    var __out: _root_.scalapb.GeneratedMessageCompanion[_] = null
    (__number: @_root_.scala.unchecked) match {
      case 1 => __out = caffe2.caffe2.TensorShape
    }
    __out
  }
  lazy val nestedMessagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] = Seq.empty
  def enumCompanionForFieldNumber(__fieldNumber: _root_.scala.Int): _root_.scalapb.GeneratedEnumCompanion[_] = throw new MatchError(__fieldNumber)
  lazy val defaultInstance = caffe2.caffe2.TensorShapes(
    shapes = _root_.scala.Seq.empty
  )
  final class Builder private (
    private val __shapes: _root_.scala.collection.immutable.VectorBuilder[caffe2.caffe2.TensorShape],
    private var `_unknownFields__`: _root_.scalapb.UnknownFieldSet.Builder
  ) extends _root_.scalapb.MessageBuilder[caffe2.caffe2.TensorShapes] {
    def merge(`_input__`: _root_.com.google.protobuf.CodedInputStream): this.type = {
      var _done__ = false
      while (!_done__) {
        val _tag__ = _input__.readTag()
        _tag__ match {
          case 0 => _done__ = true
          case 10 =>
            __shapes += _root_.scalapb.LiteParser.readMessage[caffe2.caffe2.TensorShape](_input__)
          case tag =>
            if (_unknownFields__ == null) {
              _unknownFields__ = new _root_.scalapb.UnknownFieldSet.Builder()
            }
            _unknownFields__.parseField(tag, _input__)
        }
      }
      this
    }
    def result(): caffe2.caffe2.TensorShapes = {
      caffe2.caffe2.TensorShapes(
        shapes = __shapes.result(),
        unknownFields = if (_unknownFields__ == null) _root_.scalapb.UnknownFieldSet.empty else _unknownFields__.result()
      )
    }
  }
  object Builder extends _root_.scalapb.MessageBuilderCompanion[caffe2.caffe2.TensorShapes, caffe2.caffe2.TensorShapes.Builder] {
    def apply(): Builder = new Builder(
      __shapes = new _root_.scala.collection.immutable.VectorBuilder[caffe2.caffe2.TensorShape],
      `_unknownFields__` = null
    )
    def apply(`_message__`: caffe2.caffe2.TensorShapes): Builder = new Builder(
        __shapes = new _root_.scala.collection.immutable.VectorBuilder[caffe2.caffe2.TensorShape] ++= _message__.shapes,
        `_unknownFields__` = new _root_.scalapb.UnknownFieldSet.Builder(_message__.unknownFields)
    )
  }
  def newBuilder: Builder = caffe2.caffe2.TensorShapes.Builder()
  def newBuilder(`_message__`: caffe2.caffe2.TensorShapes): Builder = caffe2.caffe2.TensorShapes.Builder(_message__)
  implicit class TensorShapesLens[UpperPB](_l: _root_.scalapb.lenses.Lens[UpperPB, caffe2.caffe2.TensorShapes]) extends _root_.scalapb.lenses.ObjectLens[UpperPB, caffe2.caffe2.TensorShapes](_l) {
    def shapes: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Seq[caffe2.caffe2.TensorShape]] = field(_.shapes)((c_, f_) => c_.copy(shapes = f_))
  }
  final val SHAPES_FIELD_NUMBER = 1
  def of(
    shapes: _root_.scala.Seq[caffe2.caffe2.TensorShape]
  ): _root_.caffe2.caffe2.TensorShapes = _root_.caffe2.caffe2.TensorShapes(
    shapes
  )
  // @@protoc_insertion_point(GeneratedMessageCompanion[caffe2.TensorShapes])
}
