// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO2

package caffe2.hsm

/** Internal Protobuf format which represents the path in the tree hierarchy for
  * each word in the vocabulary.
  */
@SerialVersionUID(0L)
final case class HierarchyProto(
    size: _root_.scala.Option[_root_.scala.Int] = _root_.scala.None,
    paths: _root_.scala.Seq[caffe2.hsm.PathProto] = _root_.scala.Seq.empty,
    unknownFields: _root_.scalapb.UnknownFieldSet = _root_.scalapb.UnknownFieldSet.empty
    ) extends scalapb.GeneratedMessage with scalapb.lenses.Updatable[HierarchyProto] {
    @transient
    private[this] var __serializedSizeCachedValue: _root_.scala.Int = 0
    private[this] def __computeSerializedValue(): _root_.scala.Int = {
      var __size = 0
      if (size.isDefined) {
        val __value = size.get
        __size += _root_.com.google.protobuf.CodedOutputStream.computeInt32Size(1, __value)
      };
      paths.foreach { __item =>
        val __value = __item
        __size += 1 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(__value.serializedSize) + __value.serializedSize
      }
      __size += unknownFields.serializedSize
      __size
    }
    override def serializedSize: _root_.scala.Int = {
      var read = __serializedSizeCachedValue
      if (read == 0) {
        read = __computeSerializedValue()
        __serializedSizeCachedValue = read
      }
      read
    }
    def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): _root_.scala.Unit = {
      size.foreach { __v =>
        val __m = __v
        _output__.writeInt32(1, __m)
      };
      paths.foreach { __v =>
        val __m = __v
        _output__.writeTag(2, 2)
        _output__.writeUInt32NoTag(__m.serializedSize)
        __m.writeTo(_output__)
      };
      unknownFields.writeTo(_output__)
    }
    def getSize: _root_.scala.Int = size.getOrElse(0)
    def clearSize: HierarchyProto = copy(size = _root_.scala.None)
    def withSize(__v: _root_.scala.Int): HierarchyProto = copy(size = Option(__v))
    def clearPaths = copy(paths = _root_.scala.Seq.empty)
    def addPaths(__vs: caffe2.hsm.PathProto*): HierarchyProto = addAllPaths(__vs)
    def addAllPaths(__vs: Iterable[caffe2.hsm.PathProto]): HierarchyProto = copy(paths = paths ++ __vs)
    def withPaths(__v: _root_.scala.Seq[caffe2.hsm.PathProto]): HierarchyProto = copy(paths = __v)
    def withUnknownFields(__v: _root_.scalapb.UnknownFieldSet) = copy(unknownFields = __v)
    def discardUnknownFields = copy(unknownFields = _root_.scalapb.UnknownFieldSet.empty)
    def getFieldByNumber(__fieldNumber: _root_.scala.Int): _root_.scala.Any = {
      (__fieldNumber: @_root_.scala.unchecked) match {
        case 1 => size.orNull
        case 2 => paths
      }
    }
    def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
      _root_.scala.Predef.require(__field.containingMessage eq companion.scalaDescriptor)
      (__field.number: @_root_.scala.unchecked) match {
        case 1 => size.map(_root_.scalapb.descriptors.PInt(_)).getOrElse(_root_.scalapb.descriptors.PEmpty)
        case 2 => _root_.scalapb.descriptors.PRepeated(paths.iterator.map(_.toPMessage).toVector)
      }
    }
    def toProtoString: _root_.scala.Predef.String = _root_.scalapb.TextFormat.printToUnicodeString(this)
    def companion = caffe2.hsm.HierarchyProto
    // @@protoc_insertion_point(GeneratedMessage[caffe2.HierarchyProto])
}

object HierarchyProto extends scalapb.GeneratedMessageCompanion[caffe2.hsm.HierarchyProto] with scalapb.HasBuilder[caffe2.hsm.HierarchyProto] {
  implicit def messageCompanion: scalapb.GeneratedMessageCompanion[caffe2.hsm.HierarchyProto] with scalapb.HasBuilder[caffe2.hsm.HierarchyProto] = this
  def merge(`_message__`: caffe2.hsm.HierarchyProto, `_input__`: _root_.com.google.protobuf.CodedInputStream): caffe2.hsm.HierarchyProto = newBuilder(_message__).merge(_input__).result()
  implicit def messageReads: _root_.scalapb.descriptors.Reads[caffe2.hsm.HierarchyProto] = _root_.scalapb.descriptors.Reads{
    case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
      _root_.scala.Predef.require(__fieldsMap.keys.forall(_.containingMessage == scalaDescriptor), "FieldDescriptor does not match message type.")
      caffe2.hsm.HierarchyProto(
        size = __fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).flatMap(_.as[_root_.scala.Option[_root_.scala.Int]]),
        paths = __fieldsMap.get(scalaDescriptor.findFieldByNumber(2).get).map(_.as[_root_.scala.Seq[caffe2.hsm.PathProto]]).getOrElse(_root_.scala.Seq.empty)
      )
    case _ => throw new RuntimeException("Expected PMessage")
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = HsmProto.javaDescriptor.getMessageTypes().get(2)
  def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = HsmProto.scalaDescriptor.messages(2)
  def messageCompanionForFieldNumber(__number: _root_.scala.Int): _root_.scalapb.GeneratedMessageCompanion[_] = {
    var __out: _root_.scalapb.GeneratedMessageCompanion[_] = null
    (__number: @_root_.scala.unchecked) match {
      case 2 => __out = caffe2.hsm.PathProto
    }
    __out
  }
  lazy val nestedMessagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] = Seq.empty
  def enumCompanionForFieldNumber(__fieldNumber: _root_.scala.Int): _root_.scalapb.GeneratedEnumCompanion[_] = throw new MatchError(__fieldNumber)
  lazy val defaultInstance = caffe2.hsm.HierarchyProto(
    size = _root_.scala.None,
    paths = _root_.scala.Seq.empty
  )
  final class Builder private (
    private var __size: _root_.scala.Option[_root_.scala.Int],
    private val __paths: _root_.scala.collection.immutable.VectorBuilder[caffe2.hsm.PathProto],
    private var `_unknownFields__`: _root_.scalapb.UnknownFieldSet.Builder
  ) extends _root_.scalapb.MessageBuilder[caffe2.hsm.HierarchyProto] {
    def merge(`_input__`: _root_.com.google.protobuf.CodedInputStream): this.type = {
      var _done__ = false
      while (!_done__) {
        val _tag__ = _input__.readTag()
        _tag__ match {
          case 0 => _done__ = true
          case 8 =>
            __size = Option(_input__.readInt32())
          case 18 =>
            __paths += _root_.scalapb.LiteParser.readMessage[caffe2.hsm.PathProto](_input__)
          case tag =>
            if (_unknownFields__ == null) {
              _unknownFields__ = new _root_.scalapb.UnknownFieldSet.Builder()
            }
            _unknownFields__.parseField(tag, _input__)
        }
      }
      this
    }
    def result(): caffe2.hsm.HierarchyProto = {
      caffe2.hsm.HierarchyProto(
        size = __size,
        paths = __paths.result(),
        unknownFields = if (_unknownFields__ == null) _root_.scalapb.UnknownFieldSet.empty else _unknownFields__.result()
      )
    }
  }
  object Builder extends _root_.scalapb.MessageBuilderCompanion[caffe2.hsm.HierarchyProto, caffe2.hsm.HierarchyProto.Builder] {
    def apply(): Builder = new Builder(
      __size = _root_.scala.None,
      __paths = new _root_.scala.collection.immutable.VectorBuilder[caffe2.hsm.PathProto],
      `_unknownFields__` = null
    )
    def apply(`_message__`: caffe2.hsm.HierarchyProto): Builder = new Builder(
        __size = _message__.size,
        __paths = new _root_.scala.collection.immutable.VectorBuilder[caffe2.hsm.PathProto] ++= _message__.paths,
        `_unknownFields__` = new _root_.scalapb.UnknownFieldSet.Builder(_message__.unknownFields)
    )
  }
  def newBuilder: Builder = caffe2.hsm.HierarchyProto.Builder()
  def newBuilder(`_message__`: caffe2.hsm.HierarchyProto): Builder = caffe2.hsm.HierarchyProto.Builder(_message__)
  implicit class HierarchyProtoLens[UpperPB](_l: _root_.scalapb.lenses.Lens[UpperPB, caffe2.hsm.HierarchyProto]) extends _root_.scalapb.lenses.ObjectLens[UpperPB, caffe2.hsm.HierarchyProto](_l) {
    def size: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Int] = field(_.getSize)((c_, f_) => c_.copy(size = Option(f_)))
    def optionalSize: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Option[_root_.scala.Int]] = field(_.size)((c_, f_) => c_.copy(size = f_))
    def paths: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Seq[caffe2.hsm.PathProto]] = field(_.paths)((c_, f_) => c_.copy(paths = f_))
  }
  final val SIZE_FIELD_NUMBER = 1
  final val PATHS_FIELD_NUMBER = 2
  def of(
    size: _root_.scala.Option[_root_.scala.Int],
    paths: _root_.scala.Seq[caffe2.hsm.PathProto]
  ): _root_.caffe2.hsm.HierarchyProto = _root_.caffe2.hsm.HierarchyProto(
    size,
    paths
  )
  // @@protoc_insertion_point(GeneratedMessageCompanion[caffe2.HierarchyProto])
}
