// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO2

package caffe2.prof_dag

object ProfDagProtoCompanion extends _root_.scalapb.GeneratedFileObject {
  lazy val dependencies: Seq[_root_.scalapb.GeneratedFileObject] = Seq.empty
  lazy val messagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] =
    Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]](
      caffe2.prof_dag.TwoNumberStatsProto,
      caffe2.prof_dag.BlobProfile,
      caffe2.prof_dag.ProfDAGProto,
      caffe2.prof_dag.ProfDAGProtos,
      caffe2.prof_dag.OpProfile
    )
  private lazy val ProtoBytes: Array[Byte] =
      scalapb.Encoding.fromBase64(scala.collection.immutable.Seq(
  """ChtjYWZmZTIvcHJvdG8vcHJvZl9kYWcucHJvdG8SBmNhZmZlMiJ7ChNUd29OdW1iZXJTdGF0c1Byb3RvEh0KBG1lYW4YASABK
  AJCCeI/BhIEbWVhblIEbWVhbhIjCgZzdGRkZXYYAiABKAJCC+I/CBIGc3RkZGV2UgZzdGRkZXYSIAoFY291bnQYAyABKANCCuI/B
  xIFY291bnRSBWNvdW50IngKC0Jsb2JQcm9maWxlEh0KBG5hbWUYASABKAlCCeI/BhIEbmFtZVIEbmFtZRJKCgpieXRlc191c2VkG
  AMgASgLMhsuY2FmZmUyLlR3b051bWJlclN0YXRzUHJvdG9CDuI/CxIJYnl0ZXNVc2VkUglieXRlc1VzZWQiyAIKDFByb2ZEQUdQc
  m90bxIdCgRuYW1lGAEgAigJQgniPwYSBG5hbWVSBG5hbWUSHQoEbWVhbhgCIAIoAkIJ4j8GEgRtZWFuUgRtZWFuEiMKBnN0ZGRld
  hgDIAIoAkIL4j8IEgZzdGRkZXZSBnN0ZGRldhJWCg5leGVjdXRpb25fdGltZRgEIAEoCzIbLmNhZmZlMi5Ud29OdW1iZXJTdGF0c
  1Byb3RvQhLiPw8SDWV4ZWN1dGlvblRpbWVSDWV4ZWN1dGlvblRpbWUSTgoOb3V0cHV0X3Byb2ZpbGUYBSADKAsyEy5jYWZmZTIuQ
  mxvYlByb2ZpbGVCEuI/DxINb3V0cHV0UHJvZmlsZVINb3V0cHV0UHJvZmlsZRItCgpleHRyYV9pbmZvGAcgAygJQg7iPwsSCWV4d
  HJhSW5mb1IJZXh0cmFJbmZvIq8BCg1Qcm9mREFHUHJvdG9zEjYKBXN0YXRzGAEgAygLMhQuY2FmZmUyLlByb2ZEQUdQcm90b0IK4
  j8HEgVzdGF0c1IFc3RhdHMSJwoIbmV0X25hbWUYAiABKAlCDOI/CRIHbmV0TmFtZVIHbmV0TmFtZRI9CglvcHNfc3RhdHMYAyADK
  AsyES5jYWZmZTIuT3BQcm9maWxlQg3iPwoSCG9wc1N0YXRzUghvcHNTdGF0cyKoAQoJT3BQcm9maWxlEhoKA2lkeBgBIAEoCUII4
  j8FEgNpZHhSA2lkeBInCghuZXRfbmFtZRgCIAEoCUIM4j8JEgduZXROYW1lUgduZXROYW1lEh0KBHR5cGUYAyABKAlCCeI/BhIEd
  HlwZVIEdHlwZRI3Cg5leGVjX3RpbWVfc2VjcxgEIAEoAkIR4j8OEgxleGVjVGltZVNlY3NSDGV4ZWNUaW1lU2Vjcw=="""
      ).mkString)
  lazy val scalaDescriptor: _root_.scalapb.descriptors.FileDescriptor = {
    val scalaProto = com.google.protobuf.descriptor.FileDescriptorProto.parseFrom(ProtoBytes)
    _root_.scalapb.descriptors.FileDescriptor.buildFrom(scalaProto, dependencies.map(_.scalaDescriptor))
  }
  lazy val javaDescriptor: com.google.protobuf.Descriptors.FileDescriptor = {
    val javaProto = com.google.protobuf.DescriptorProtos.FileDescriptorProto.parseFrom(ProtoBytes)
    com.google.protobuf.Descriptors.FileDescriptor.buildFrom(javaProto, Array(
    ))
  }
  @deprecated("Use javaDescriptor instead. In a future version this will refer to scalaDescriptor.", "ScalaPB 0.5.47")
  def descriptor: com.google.protobuf.Descriptors.FileDescriptor = javaDescriptor
}