// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO2

package caffe2.predictor_consts

object PredictorConstsProto extends _root_.scalapb.GeneratedFileObject {
  lazy val dependencies: Seq[_root_.scalapb.GeneratedFileObject] = Seq.empty
  lazy val messagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] =
    Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]](
      caffe2.predictor_consts.PredictorConsts
    )
  private lazy val ProtoBytes: Array[Byte] =
      scalapb.Encoding.fromBase64(scala.collection.immutable.Seq(
  """CiNjYWZmZTIvcHJvdG8vcHJlZGljdG9yX2NvbnN0cy5wcm90bxIGY2FmZmUyIssJCg9QcmVkaWN0b3JDb25zdHMSQQoMTUVUQ
  V9ORVRfREVGGAEgASgJOg4hIU1FVEFfTkVUX0RFRkIP4j8MEgptRVRBTkVUREVGUgpNRVRBTkVUREVGElsKElBSRURJQ1RPUl9EQ
  lJFQURFUhgCIAEoCToUISFQUkVESUNUT1JfREJSRUFERVJCFuI/ExIRcFJFRElDVE9SREJSRUFERVJSEVBSRURJQ1RPUkRCUkVBR
  EVSEl8KFFBBUkFNRVRFUlNfQkxPQl9UWVBFGAMgASgJOhRQQVJBTUVURVJTX0JMT0JfVFlQRUIX4j8UEhJwQVJBTUVURVJTQkxPQ
  lRZUEVSElBBUkFNRVRFUlNCTE9CVFlQRRJPChBJTlBVVFNfQkxPQl9UWVBFGAQgASgJOhBJTlBVVFNfQkxPQl9UWVBFQhPiPxASD
  mlOUFVUU0JMT0JUWVBFUg5JTlBVVFNCTE9CVFlQRRJTChFPVVRQVVRTX0JMT0JfVFlQRRgFIAEoCToRT1VUUFVUU19CTE9CX1RZU
  EVCFOI/ERIPb1VUUFVUU0JMT0JUWVBFUg9PVVRQVVRTQkxPQlRZUEUSXQoUR0xPQkFMX0lOSVRfTkVUX1RZUEUYBiABKAk6FEdMT
  0JBTF9JTklUX05FVF9UWVBFQhbiPxMSEWdMT0JBTElOSVRORVRUWVBFUhFHTE9CQUxJTklUTkVUVFlQRRJhChVQUkVESUNUX0lOS
  VRfTkVUX1RZUEUYByABKAk6FVBSRURJQ1RfSU5JVF9ORVRfVFlQRUIX4j8UEhJwUkVESUNUSU5JVE5FVFRZUEVSElBSRURJQ1RJT
  klUTkVUVFlQRRJPChBQUkVESUNUX05FVF9UWVBFGAggASgJOhBQUkVESUNUX05FVF9UWVBFQhPiPxASDnBSRURJQ1RORVRUWVBFU
  g5QUkVESUNUTkVUVFlQRRJRChBTSU5HTEVfUFJFRElDVE9SGAkgASgJOhBTSU5HTEVfUFJFRElDVE9SQhTiPxESD3NJTkdMRVBSR
  URJQ1RPUlIPU0lOR0xFUFJFRElDVE9SEk0KD01VTFRJX1BSRURJQ1RPUhgKIAEoCToPTVVMVElfUFJFRElDVE9SQhPiPxASDm1VT
  FRJUFJFRElDVE9SUg5NVUxUSVBSRURJQ1RPUhJdChRUUkFJTl9JTklUX1BMQU5fVFlQRRgLIAEoCToUVFJBSU5fSU5JVF9QTEFOX
  1RZUEVCFuI/ExIRdFJBSU5JTklUUExBTlRZUEVSEVRSQUlOSU5JVFBMQU5UWVBFEksKD1RSQUlOX1BMQU5fVFlQRRgMIAEoCToPV
  FJBSU5fUExBTl9UWVBFQhLiPw8SDXRSQUlOUExBTlRZUEVSDVRSQUlOUExBTlRZUEUSSwoPU0hBUEVfSU5GT19CTE9CGA0gASgJO
  g9TSEFQRV9JTkZPX0JMT0JCEuI/DxINc0hBUEVJTkZPQkxPQlINU0hBUEVJTkZPQkxPQhJjChRERUZFUlJFRF9CTE9CX1JFQURFU
  hgOIAEoCToYX19ERUZFUlJFRF9CTE9CX1JFQURFUl9fQhfiPxQSEmRFRkVSUkVEQkxPQlJFQURFUlISREVGRVJSRURCTE9CUkVBR
  EVS"""
      ).mkString)
  lazy val scalaDescriptor: _root_.scalapb.descriptors.FileDescriptor = {
    val scalaProto = com.google.protobuf.descriptor.FileDescriptorProto.parseFrom(ProtoBytes)
    _root_.scalapb.descriptors.FileDescriptor.buildFrom(scalaProto, dependencies.map(_.scalaDescriptor))
  }
  lazy val javaDescriptor: com.google.protobuf.Descriptors.FileDescriptor = {
    val javaProto = com.google.protobuf.DescriptorProtos.FileDescriptorProto.parseFrom(ProtoBytes)
    com.google.protobuf.Descriptors.FileDescriptor.buildFrom(javaProto, Array(
    ))
  }
  @deprecated("Use javaDescriptor instead. In a future version this will refer to scalaDescriptor.", "ScalaPB 0.5.47")
  def descriptor: com.google.protobuf.Descriptors.FileDescriptor = javaDescriptor
}